nohup: ignoring input
12/14/2022 14:04:55 - WARNING - __main__ -   Process rank: -1, device: cuda, n_gpu: 1, distributed training: False, 16-bits training: False
Traceback (most recent call last):
  File "run_musique.py", line 679, in <module>
    main()
  File "run_musique.py", line 578, in main
    tokenizer = tokenizer_class.from_pretrained(args.tokenizer_name if args.tokenizer_name else args.model_name_or_path,
  File "/home/mxdong/anaconda3/envs/dalle38/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1744, in from_pretrained
    resolved_vocab_files[file_id] = cached_path(
  File "/home/mxdong/anaconda3/envs/dalle38/lib/python3.8/site-packages/transformers/utils/hub.py", line 284, in cached_path
    output_path = get_from_cache(
  File "/home/mxdong/anaconda3/envs/dalle38/lib/python3.8/site-packages/transformers/utils/hub.py", line 501, in get_from_cache
    r = requests.head(url, headers=headers, allow_redirects=False, proxies=proxies, timeout=etag_timeout)
  File "/home/mxdong/anaconda3/envs/dalle38/lib/python3.8/site-packages/requests/api.py", line 100, in head
    return request("head", url, **kwargs)
  File "/home/mxdong/anaconda3/envs/dalle38/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/mxdong/anaconda3/envs/dalle38/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/mxdong/anaconda3/envs/dalle38/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/mxdong/anaconda3/envs/dalle38/lib/python3.8/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/mxdong/anaconda3/envs/dalle38/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/mxdong/anaconda3/envs/dalle38/lib/python3.8/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/mxdong/anaconda3/envs/dalle38/lib/python3.8/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/home/mxdong/anaconda3/envs/dalle38/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/home/mxdong/anaconda3/envs/dalle38/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/home/mxdong/anaconda3/envs/dalle38/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/home/mxdong/anaconda3/envs/dalle38/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/home/mxdong/anaconda3/envs/dalle38/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/home/mxdong/anaconda3/envs/dalle38/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt
